"""Provisional Shaelvien Lite seed data.

These records are vertical-slice placeholders. They are intentionally
data-driven so Owner-approved canon can replace names, rewards, or mechanics
without replacing the game engine.
"""

ATTRIBUTES = [
    "Strength",
    "Agility",
    "Endurance",
    "Intellect",
    "Awareness",
    "Presence",
]

SKILLS = [
    "Athletics",
    "Stealth",
    "Investigation",
    "Survival",
    "Medicine",
    "Persuasion",
    "Intimidation",
    "Crafting",
    "Arcana",
    "Lore",
]

ROLES = {
    "vanguard": {
        "name": "Vanguard",
        "origin": "Outpost sworn",
        "portrait": "assets/hero-vanguard.svg",
        "tier": "Founding",
        "attributes": {
            "Strength": 15,
            "Agility": 10,
            "Endurance": 14,
            "Intellect": 10,
            "Awareness": 11,
            "Presence": 12,
        },
        "skills": {"Athletics": 2, "Intimidation": 1, "Survival": 1},
        "equipment": {
            "weapon": "iron_saber",
            "off_hand": "round_shield",
            "body": "padded_coat",
            "consumables": ["healing_draught"],
        },
        "biography": "A steady front-line defender assigned to Emberhall's first patrols.",
    },
    "pathfinder": {
        "name": "Pathfinder",
        "origin": "Road scout",
        "portrait": "assets/hero-pathfinder.svg",
        "tier": "Founding",
        "attributes": {
            "Strength": 10,
            "Agility": 15,
            "Endurance": 12,
            "Intellect": 11,
            "Awareness": 14,
            "Presence": 10,
        },
        "skills": {"Stealth": 2, "Investigation": 1, "Survival": 2},
        "equipment": {
            "weapon": "short_bow",
            "off_hand": "field_knife",
            "body": "scout_leathers",
            "feet": "traveler_boots",
            "consumables": ["stamina_tonic"],
        },
        "biography": "A quiet route-finder who reads old roads and fresh tracks with equal care.",
    },
    "arcanist": {
        "name": "Arcanist",
        "origin": "Ruin-taught adept",
        "portrait": "assets/hero-arcanist.svg",
        "tier": "Founding",
        "attributes": {
            "Strength": 8,
            "Agility": 11,
            "Endurance": 10,
            "Intellect": 16,
            "Awareness": 13,
            "Presence": 12,
        },
        "skills": {"Arcana": 2, "Lore": 2, "Investigation": 1},
        "equipment": {
            "weapon": "focus_staff",
            "body": "threadbare_robes",
            "accessory": "copper_focus",
            "consumables": ["focus_tea"],
        },
        "biography": "A cautious scholar of restrained magical technology and weathered relics.",
    },
}

ITEMS = {
    "ember_shard": {
        "item_id": "ember_shard",
        "name": "Ember Shard",
        "category": "resource",
        "mass": 0.1,
        "quality": "common",
        "durability": None,
        "description": "A warm mineral splinter used by Emberhall crafters.",
        "mechanical_effects": {"resource": "ember"},
        "value": 3,
        "ownership_status": "owned",
    },
    "trail_rations": {
        "item_id": "trail_rations",
        "name": "Trail Rations",
        "category": "supply",
        "mass": 1,
        "quality": "common",
        "durability": None,
        "description": "Hard bread, smoked roots, and sealed broth paste.",
        "mechanical_effects": {"rest_stamina": 2},
        "value": 4,
        "ownership_status": "owned",
    },
    "iron_ore": {
        "item_id": "iron_ore",
        "name": "Iron Ore",
        "category": "resource",
        "mass": 2,
        "quality": "common",
        "durability": None,
        "description": "Rough mine ore suitable for simple repairs.",
        "mechanical_effects": {"resource": "ore"},
        "value": 5,
        "ownership_status": "owned",
    },
    "old_map_fragment": {
        "item_id": "old_map_fragment",
        "name": "Old Map Fragment",
        "category": "quest",
        "mass": 0,
        "quality": "worn",
        "durability": None,
        "description": "A partial route map with burned edges.",
        "mechanical_effects": {"unlock_hint": "mine"},
        "value": 1,
        "ownership_status": "owned",
    },
    "guild_token": {
        "item_id": "guild_token",
        "name": "Guild Token",
        "category": "quest",
        "mass": 0.1,
        "quality": "common",
        "durability": None,
        "description": "A stamped token accepted by Emberhall's quest hall.",
        "mechanical_effects": {"quest_rep": 1},
        "value": 2,
        "ownership_status": "owned",
    },
    "camp_timber": {
        "item_id": "camp_timber",
        "name": "Camp Timber",
        "category": "resource",
        "mass": 3,
        "quality": "common",
        "durability": None,
        "description": "Bundled treated timber for outpost improvements.",
        "mechanical_effects": {"resource": "timber"},
        "value": 6,
        "ownership_status": "owned",
    },
    "clean_bandage": {
        "item_id": "clean_bandage",
        "name": "Clean Bandage",
        "category": "supply",
        "mass": 0.2,
        "quality": "common",
        "durability": None,
        "description": "Sterile cloth for field treatment.",
        "mechanical_effects": {"medicine_bonus": 1},
        "value": 2,
        "ownership_status": "owned",
    },
    "lamp_oil": {
        "item_id": "lamp_oil",
        "name": "Lamp Oil",
        "category": "supply",
        "mass": 0.5,
        "quality": "common",
        "durability": None,
        "description": "Sealed oil useful in mines and ruins.",
        "mechanical_effects": {"darkness_penalty_reduction": 1},
        "value": 3,
        "ownership_status": "owned",
    },
    "field_tools": {
        "item_id": "field_tools",
        "name": "Field Tools",
        "category": "tool",
        "mass": 2,
        "quality": "common",
        "durability": 20,
        "description": "A compact repair and excavation kit.",
        "mechanical_effects": {"Crafting": 1},
        "value": 12,
        "ownership_status": "owned",
    },
    "shrine_rubbing": {
        "item_id": "shrine_rubbing",
        "name": "Shrine Rubbing",
        "category": "quest",
        "mass": 0,
        "quality": "fragile",
        "durability": None,
        "description": "Charcoal markings copied from old stonework.",
        "mechanical_effects": {"Lore": 1},
        "value": 2,
        "ownership_status": "owned",
    },
    "iron_saber": {
        "item_id": "iron_saber",
        "name": "Iron Saber",
        "category": "weapon",
        "mass": 3,
        "quality": "common",
        "durability": 30,
        "description": "A serviceable outpost blade.",
        "mechanical_effects": {"attack_attribute": "Strength", "damage": "1d8"},
        "value": 20,
        "ownership_status": "owned",
    },
    "short_bow": {
        "item_id": "short_bow",
        "name": "Short Bow",
        "category": "weapon",
        "mass": 2,
        "quality": "common",
        "durability": 24,
        "description": "A compact bow for road patrols.",
        "mechanical_effects": {"attack_attribute": "Agility", "damage": "1d6"},
        "value": 18,
        "ownership_status": "owned",
    },
    "field_knife": {
        "item_id": "field_knife",
        "name": "Field Knife",
        "category": "weapon",
        "mass": 1,
        "quality": "common",
        "durability": 20,
        "description": "A reliable blade for camp work and close scrapes.",
        "mechanical_effects": {"attack_attribute": "Agility", "damage": "1d4"},
        "value": 8,
        "ownership_status": "owned",
    },
    "focus_staff": {
        "item_id": "focus_staff",
        "name": "Focus Staff",
        "category": "weapon",
        "mass": 2,
        "quality": "common",
        "durability": 22,
        "description": "A staff capped with conductive copper.",
        "mechanical_effects": {"attack_attribute": "Intellect", "damage": "1d6"},
        "value": 22,
        "ownership_status": "owned",
    },
    "smith_hammer": {
        "item_id": "smith_hammer",
        "name": "Smith Hammer",
        "category": "weapon",
        "mass": 4,
        "quality": "common",
        "durability": 35,
        "description": "A heavy hammer that doubles as a brutal tool.",
        "mechanical_effects": {"attack_attribute": "Strength", "damage": "1d8"},
        "value": 16,
        "ownership_status": "owned",
    },
    "guard_spear": {
        "item_id": "guard_spear",
        "name": "Guard Spear",
        "category": "weapon",
        "mass": 4,
        "quality": "common",
        "durability": 28,
        "description": "A long spear used by outpost watches.",
        "mechanical_effects": {"attack_attribute": "Strength", "damage": "1d6", "range": "Near"},
        "value": 15,
        "ownership_status": "owned",
    },
    "round_shield": {
        "item_id": "round_shield",
        "name": "Round Shield",
        "category": "armor",
        "mass": 4,
        "quality": "common",
        "durability": 30,
        "description": "A timber and iron shield.",
        "mechanical_effects": {"defense": 1},
        "value": 14,
        "ownership_status": "owned",
    },
    "padded_coat": {
        "item_id": "padded_coat",
        "name": "Padded Coat",
        "category": "armor",
        "mass": 5,
        "quality": "common",
        "durability": 28,
        "description": "Layered cloth armor reinforced for travel.",
        "mechanical_effects": {"soak": 1},
        "value": 12,
        "ownership_status": "owned",
    },
    "scout_leathers": {
        "item_id": "scout_leathers",
        "name": "Scout Leathers",
        "category": "armor",
        "mass": 4,
        "quality": "common",
        "durability": 24,
        "description": "Quiet leathers suited to the roads.",
        "mechanical_effects": {"Stealth": 1},
        "value": 14,
        "ownership_status": "owned",
    },
    "threadbare_robes": {
        "item_id": "threadbare_robes",
        "name": "Threadbare Robes",
        "category": "armor",
        "mass": 2,
        "quality": "worn",
        "durability": 18,
        "description": "Old robes sewn with dull conductive thread.",
        "mechanical_effects": {"Arcana": 1},
        "value": 10,
        "ownership_status": "owned",
    },
    "traveler_boots": {
        "item_id": "traveler_boots",
        "name": "Traveler Boots",
        "category": "armor",
        "mass": 2,
        "quality": "common",
        "durability": 22,
        "description": "Boots made for hard roads.",
        "mechanical_effects": {"Survival": 1},
        "value": 9,
        "ownership_status": "owned",
    },
    "iron_cap": {
        "item_id": "iron_cap",
        "name": "Iron Cap",
        "category": "armor",
        "mass": 2,
        "quality": "common",
        "durability": 26,
        "description": "A simple helm from the guard stores.",
        "mechanical_effects": {"soak": 1},
        "value": 11,
        "ownership_status": "owned",
    },
    "copper_focus": {
        "item_id": "copper_focus",
        "name": "Copper Focus",
        "category": "accessory",
        "mass": 0.2,
        "quality": "common",
        "durability": 18,
        "description": "A small conductive ring used for controlled workings.",
        "mechanical_effects": {"Arcana": 1},
        "value": 13,
        "ownership_status": "owned",
    },
    "healing_draught": {
        "item_id": "healing_draught",
        "name": "Healing Draught",
        "category": "consumable",
        "mass": 0.2,
        "quality": "common",
        "durability": None,
        "description": "A bitter red draught that restores a small amount of health.",
        "mechanical_effects": {"heal": 8},
        "value": 10,
        "ownership_status": "owned",
    },
    "focus_tea": {
        "item_id": "focus_tea",
        "name": "Focus Tea",
        "category": "consumable",
        "mass": 0.1,
        "quality": "common",
        "durability": None,
        "description": "Steeped leaves that settle the mind.",
        "mechanical_effects": {"next_check": {"Intellect": 1}},
        "value": 8,
        "ownership_status": "owned",
    },
    "stamina_tonic": {
        "item_id": "stamina_tonic",
        "name": "Stamina Tonic",
        "category": "consumable",
        "mass": 0.2,
        "quality": "common",
        "durability": None,
        "description": "A sharp tonic that restores stamina.",
        "mechanical_effects": {"stamina": 6},
        "value": 8,
        "ownership_status": "owned",
    },
    "antidote_salve": {
        "item_id": "antidote_salve",
        "name": "Antidote Salve",
        "category": "consumable",
        "mass": 0.2,
        "quality": "common",
        "durability": None,
        "description": "A green salve that clears common toxins.",
        "mechanical_effects": {"remove_condition": "poisoned"},
        "value": 9,
        "ownership_status": "owned",
    },
    "smoke_vial": {
        "item_id": "smoke_vial",
        "name": "Smoke Vial",
        "category": "consumable",
        "mass": 0.2,
        "quality": "common",
        "durability": None,
        "description": "A small glass vial that bursts into gray smoke.",
        "mechanical_effects": {"retreat_bonus": 2},
        "value": 7,
        "ownership_status": "owned",
    },
}

REGION = {
    "region_id": "emberhall_reach",
    "name": "Emberhall Reach",
    "settlement": {
        "location_id": "emberhall_outpost",
        "name": "Emberhall Outpost",
        "kind": "settlement",
        "art": "assets/location-emberhall.svg",
        "description": "A fortified lantern settlement built from black timber, salvaged stone, and warm copper fixtures.",
        "services": ["inn", "blacksmith", "healer", "merchant", "guild_hall", "training_area", "personal_camp"],
    },
    "locations": {
        "forest_road": {
            "location_id": "forest_road",
            "name": "Forest Road",
            "kind": "adventure",
            "art": "assets/location-forest-road.svg",
            "summary": "A wet trade road where old mile stones hum after sunset.",
            "exploration_event": "Fresh cart ruts stop beside clawed bootprints.",
            "social_event": "A shaken courier insists someone wearing a guard cloak searched the road.",
            "combat_event": "A road cutpurse tests whether the patrol is alone.",
            "check": {"attribute": "Awareness", "skill": "Investigation", "difficulty": 12},
            "enemy": "road_cutpurse",
            "rewards": {"items": {"camp_timber": 2, "guild_token": 1}, "currency": 12, "resources": {"timber": 2}},
        },
        "abandoned_mine": {
            "location_id": "abandoned_mine",
            "name": "Abandoned Mine",
            "kind": "adventure",
            "art": "assets/location-mine.svg",
            "summary": "A sealed ore face split by stale air and copper-thread roots.",
            "exploration_event": "A lift chain has been cut recently, not rusted through.",
            "social_event": "A hidden mark near the lift matches a merchant tally sign.",
            "combat_event": "Mine skulks move in the dark beyond the lantern line.",
            "check": {"attribute": "Endurance", "skill": "Survival", "difficulty": 13},
            "enemy": "mine_skulk",
            "rewards": {"items": {"iron_ore": 3, "lamp_oil": 1}, "currency": 15, "resources": {"ore": 3}},
        },
        "ruined_shrine": {
            "location_id": "ruined_shrine",
            "name": "Ruined Shrine",
            "kind": "adventure",
            "art": "assets/location-shrine.svg",
            "summary": "A broken stone circle around a quiet, glassy altar.",
            "exploration_event": "Dust gathers around untouched footfalls in a perfect ring.",
            "social_event": "The healer recognizes the altar marks as old warning script, not prayer.",
            "combat_event": "A hollow prowler folds itself from shrine shadow.",
            "check": {"attribute": "Intellect", "skill": "Lore", "difficulty": 14},
            "enemy": "hollow_prowler",
            "rewards": {"items": {"shrine_rubbing": 1, "ember_shard": 2}, "currency": 10, "resources": {"ember": 2}},
        },
        "bandit_camp": {
            "location_id": "bandit_camp",
            "name": "Bandit Camp",
            "kind": "adventure",
            "art": "assets/location-bandit-camp.svg",
            "summary": "A smoke-hidden camp tucked behind split boulders and stripped banners.",
            "exploration_event": "The camp has more ration crates than its numbers explain.",
            "social_event": "A captive scout says the leader is waiting for a mine signal.",
            "combat_event": "The bandit leader rallies the camp around a stolen guild banner.",
            "check": {"attribute": "Presence", "skill": "Intimidation", "difficulty": 15},
            "enemy": "kest_vane",
            "rewards": {"items": {"old_map_fragment": 1, "healing_draught": 1}, "currency": 25, "resources": {"ore": 1, "timber": 1}},
        },
    },
}

NPCS = {
    "npc_innkeeper": {
        "npc_id": "npc_innkeeper",
        "name": "Mara Vell",
        "role": "Innkeeper",
        "personality_summary": "Warm, observant, practical, and protective of travelers.",
        "disposition": "cautiously helpful",
        "known_facts": ["Road traffic has thinned.", "A courier arrived frightened after dusk."],
        "quest_relationships": ["q_forest_road"],
        "conversation_memory": [],
        "permitted_knowledge_boundaries": "Can discuss travelers, rumors, room ledgers, and public settlement mood. Cannot reveal guard plans, hidden shrine lore, or mine records.",
    },
    "npc_blacksmith": {
        "npc_id": "npc_blacksmith",
        "name": "Brannic Kohr",
        "role": "Blacksmith",
        "personality_summary": "Blunt, exacting, reliable, and skeptical of shortcuts.",
        "disposition": "neutral",
        "known_facts": ["Ore quality changed last month.", "A broken spear point came from the mine road."],
        "quest_relationships": ["q_mine_echoes"],
        "conversation_memory": [],
        "permitted_knowledge_boundaries": "Can discuss tools, weapons, ore, repairs, and trade metal. Cannot identify occult symbols beyond material observations.",
    },
    "npc_healer": {
        "npc_id": "npc_healer",
        "name": "Sella Iven",
        "role": "Healer",
        "personality_summary": "Quiet, precise, merciful, and careful with fear.",
        "disposition": "helpful",
        "known_facts": ["Several guards returned with sleep loss.", "Shrine dust caused cold burns."],
        "quest_relationships": ["q_shrine_marks"],
        "conversation_memory": [],
        "permitted_knowledge_boundaries": "Can discuss injuries, symptoms, remedies, and shrine-related medical evidence. Cannot provide military patrol routes or merchant finances.",
    },
    "npc_merchant": {
        "npc_id": "npc_merchant",
        "name": "Tovin Rusk",
        "role": "Merchant",
        "personality_summary": "Polished, nervous, opportunistic, and detail-minded.",
        "disposition": "guarded",
        "known_facts": ["Supply crates went missing near the road.", "Bandits know which wagons carry ore."],
        "quest_relationships": ["q_bandit_pressure"],
        "conversation_memory": [],
        "permitted_knowledge_boundaries": "Can discuss prices, caravan schedules he owns, missing goods, and trade gossip. Cannot know private guild orders or healer notes.",
    },
    "npc_guild_rep": {
        "npc_id": "npc_guild_rep",
        "name": "Ilyra Dain",
        "role": "Guild Representative",
        "personality_summary": "Formal, steady, encouraging, and mission-focused.",
        "disposition": "supportive",
        "known_facts": ["The Forest Road must reopen.", "The outpost will sponsor proven adventurers."],
        "quest_relationships": ["q_forest_road", "q_outpost_rebuild"],
        "conversation_memory": [],
        "permitted_knowledge_boundaries": "Can discuss official quests, reward terms, guild priorities, and public reports. Cannot invent ancient canon or reveal facts not earned in play.",
    },
    "npc_guard_scout": {
        "npc_id": "npc_guard_scout",
        "name": "Oren Vale",
        "role": "Guard Scout",
        "personality_summary": "Tired, honest, alert, and uncomfortable with politics.",
        "disposition": "wary but respectful",
        "known_facts": ["A false guard cloak was seen at the road.", "Smoke has risen from the ridge camp."],
        "quest_relationships": ["q_forest_road", "q_bandit_pressure"],
        "conversation_memory": [],
        "permitted_knowledge_boundaries": "Can discuss patrol observations, visible threats, and scouting impressions. Cannot disclose sealed orders or private civilian records.",
    },
}

QUESTS = {
    "q_forest_road": {
        "quest_id": "q_forest_road",
        "name": "Lanterns on the Forest Road",
        "giver_npc_id": "npc_guild_rep",
        "initial_status": "available",
        "steps": ["speak_guild", "travel_forest_road", "investigate_tracks", "defeat_road_cutpurse", "return_camp"],
        "unlock_location": "forest_road",
        "rewards": {"experience": 40, "currency": 20, "items": {"camp_timber": 1}},
    },
    "q_mine_echoes": {
        "quest_id": "q_mine_echoes",
        "name": "Echoes Below the Mine",
        "giver_npc_id": "npc_blacksmith",
        "initial_status": "locked",
        "steps": ["unlock_mine", "travel_mine", "secure_ore"],
        "unlock_location": "abandoned_mine",
        "rewards": {"experience": 55, "currency": 25, "items": {"iron_ore": 2}},
    },
    "q_shrine_marks": {
        "quest_id": "q_shrine_marks",
        "name": "Marks at the Ruined Shrine",
        "giver_npc_id": "npc_healer",
        "initial_status": "locked",
        "steps": ["unlock_shrine", "study_marks", "bring_rubbing"],
        "unlock_location": "ruined_shrine",
        "rewards": {"experience": 60, "currency": 20, "items": {"focus_tea": 1}},
    },
    "q_bandit_pressure": {
        "quest_id": "q_bandit_pressure",
        "name": "Pressure at the Ridge Camp",
        "giver_npc_id": "npc_guard_scout",
        "initial_status": "locked",
        "steps": ["unlock_bandit_camp", "confront_leader"],
        "unlock_location": "bandit_camp",
        "rewards": {"experience": 85, "currency": 45, "items": {"guard_spear": 1}},
    },
    "q_outpost_rebuild": {
        "quest_id": "q_outpost_rebuild",
        "name": "A Camp Worth Returning To",
        "giver_npc_id": "npc_guild_rep",
        "initial_status": "available",
        "steps": ["collect_supplies", "upgrade_structure"],
        "unlock_location": "emberhall_outpost",
        "rewards": {"experience": 25, "currency": 10, "items": {"guild_token": 1}},
    },
}

ENEMIES = {
    "road_cutpurse": {
        "enemy_id": "road_cutpurse",
        "name": "Road Cutpurse",
        "type": "skirmisher",
        "level": 1,
        "health": 14,
        "defense": 11,
        "attack_bonus": 3,
        "damage": "1d6",
        "range_band": "Near",
        "rewards": {"experience": 20, "currency": 8, "items": {"trail_rations": 1}},
    },
    "mine_skulk": {
        "enemy_id": "mine_skulk",
        "name": "Mine Skulk",
        "type": "lurker",
        "level": 1,
        "health": 16,
        "defense": 12,
        "attack_bonus": 3,
        "damage": "1d6",
        "range_band": "Engaged",
        "rewards": {"experience": 24, "currency": 5, "items": {"iron_ore": 1}},
    },
    "hollow_prowler": {
        "enemy_id": "hollow_prowler",
        "name": "Hollow Prowler",
        "type": "shade",
        "level": 2,
        "health": 18,
        "defense": 13,
        "attack_bonus": 4,
        "damage": "1d8",
        "range_band": "Near",
        "rewards": {"experience": 30, "currency": 4, "items": {"ember_shard": 1}},
    },
    "kest_vane": {
        "enemy_id": "kest_vane",
        "name": "Kest Vane, Ridge Captain",
        "type": "introductory_boss",
        "level": 3,
        "health": 26,
        "defense": 14,
        "attack_bonus": 5,
        "damage": "1d8",
        "range_band": "Near",
        "rewards": {"experience": 60, "currency": 18, "items": {"old_map_fragment": 1}},
    },
}

CAMP_STRUCTURES = {
    "quarters": {
        "structure_id": "quarters",
        "name": "Quarters",
        "level": 0,
        "max_level": 3,
        "benefit": "Increases available character slots and improves rest.",
        "upgrade_requirements": {"currency": 10, "resources": {"timber": 1}},
        "prerequisites": {},
    },
    "storage": {
        "structure_id": "storage",
        "name": "Storage",
        "level": 0,
        "max_level": 3,
        "benefit": "Increases inventory capacity.",
        "upgrade_requirements": {"currency": 8, "resources": {"timber": 1}},
        "prerequisites": {},
    },
    "workshop": {
        "structure_id": "workshop",
        "name": "Workshop",
        "level": 0,
        "max_level": 3,
        "benefit": "Unlocks crafting and repair functions.",
        "upgrade_requirements": {"currency": 12, "resources": {"ore": 1, "timber": 1}},
        "prerequisites": {"storage": 1},
    },
    "training_yard": {
        "structure_id": "training_yard",
        "name": "Training Yard",
        "level": 0,
        "max_level": 3,
        "benefit": "Unlocks skill development.",
        "upgrade_requirements": {"currency": 12, "resources": {"timber": 1}},
        "prerequisites": {"quarters": 1},
    },
    "healing_tent": {
        "structure_id": "healing_tent",
        "name": "Healing Tent",
        "level": 0,
        "max_level": 3,
        "benefit": "Improves recovery between adventures.",
        "upgrade_requirements": {"currency": 10, "resources": {"timber": 1}},
        "prerequisites": {},
    },
    "planning_table": {
        "structure_id": "planning_table",
        "name": "Planning Table",
        "level": 0,
        "max_level": 3,
        "benefit": "Reveals additional quests and map information.",
        "upgrade_requirements": {"currency": 10, "resources": {"timber": 1}},
        "prerequisites": {"quarters": 1},
    },
}

PRODUCT_CATALOG_PLACEHOLDERS = {
    "cosmetic_portrait_pack": {"name": "Portrait Pack Placeholder", "enabled": False},
    "camp_theme_pack": {"name": "Camp Theme Placeholder", "enabled": False},
    "expanded_ai_memory": {"name": "Expanded AI Memory Placeholder", "enabled": False},
    "private_party_world": {"name": "Private Party World Placeholder", "enabled": False},
}
