from __future__ import annotations

import re
from pathlib import Path

from rist_css_authority import FINAL_AUTHORITY, SOURCES

ROOT = Path(__file__).resolve().parent
CSS_SOURCE_DIR = ROOT / "css-source"
OUTPUT = ROOT / "wwwroot" / "css" / "rist.css"
IMPORT_RE = re.compile(r"@import\s+url\((?:['\"])?([^)'\"]+)(?:['\"])?\)\s*;", re.I)


def source_path(name: str) -> Path:
    """Resolve a repository-owned CSS source without treating stale snapshots as build truth."""
    clean = name.split("?", 1)[0].lstrip("./")
    candidate = (CSS_SOURCE_DIR / clean).resolve()
    root = CSS_SOURCE_DIR.resolve()
    if candidate != root and root not in candidate.parents:
        raise RuntimeError(f"CSS source escapes canonical source root: {name}")
    return candidate


def inline_imports(text: str, stack: tuple[str, ...]) -> str:
    def replace(match: re.Match[str]) -> str:
        raw = match.group(1)
        if raw.startswith(("http://", "https://", "data:")):
            raise RuntimeError(f"External CSS import is not allowed: {raw}")
        name = raw.split("?", 1)[0].lstrip("./")
        if name in stack:
            raise RuntimeError(f"CSS import cycle: {' -> '.join(stack + (name,))}")
        path = source_path(name)
        if not path.exists() or not path.is_file():
            raise FileNotFoundError(f"Missing canonical CSS import: {path}")
        return inline_imports(path.read_text(encoding="utf-8"), stack + (name,))

    return IMPORT_RE.sub(replace, text)


def main() -> None:
    sections = [
        "/* AUTO-GENERATED by apps/rist-world/prepare_css.py. */",
        "/* rist.css is the only runtime stylesheet; canonical inputs live in apps/rist-world/css-source/. */",
    ]
    for name in SOURCES:
        path = source_path(name)
        if not path.exists() or not path.is_file():
            raise FileNotFoundError(f"Missing canonical CSS source: {path}")
        body = inline_imports(path.read_text(encoding="utf-8"), (name,))
        sections.append(f"\n/* SOURCE: {name} */\n{body}")
    sections.append(FINAL_AUTHORITY)
    output = "\n".join(sections).rstrip() + "\n"
    if "@import" in output:
        raise RuntimeError("rist.css still contains @import")
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT} from {len(SOURCES)} canonical sources in {CSS_SOURCE_DIR}")


if __name__ == "__main__":
    main()
