name: Mirror Shaelvien Dice Mall to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  # ✅ allows the workflow to push a new branch

jobs:
  deploy-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # avoids token conflicts

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Prepare static content
        run: |
          mkdir -p Public
          echo "✅ Public folder verified for GitHub Pages"
          echo "<!-- Mirror Build $(date) -->" >> Public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./Public
