name: Deploy Shaelvien Dice Mall to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build (optional)
        run: |
          echo "✅ Build complete - add custom build commands here if needed."

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ShaelvienDiceGroup
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      - name: Notify Discord on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\":\"ReLiC Bot\",\"content\":\"✅ **Deployment successful** for Shaelvien DiceMall — https://relicgamemaster.com\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\":\"ReLiC Bot\",\"content\":\"❌ **Deployment failed**. Check GitHub Actions logs: https://github.com/${{ github.repository }}/actions\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}


          

